# The URL the site will be built for
base_url = "https://vanguyen.dev"
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", a search index is built from the pages and section content for `default_language`.
build_search_index = false


[languages.en]
title = "vanbuncha"
description = "Personal site for documenting life and stuff."
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
    { name = "tags", feed = true, lang = "en" },
    { name = "categories", feed = true, lang = "en" },
]

[languages.en.translations]
projects = "Projects"
blog = "Blog"
about = "About"
recent_projects = "Recent Projects"
more_projects = "More Projects"
recent_blog_posts = "Recent Blog Posts"
more_blog_posts = "More blog posts"
tag = "Tag"
tags = "Tags"
to_all_tags = "To all tags"
category = "Category"
categories = "Categories"
to_all_categories = "To all categories"
view_by = "View by"
other = "Other"
minute = "min"
prev_page = "To newer posts"
next_page = "To older posts"
date_format = "%B %e, %Y"

[extra]
env = "ZOLA_ENV"
color_mode = "auto"

menu_items = [
    { name = "projects", url = "$LANG_BASE_URL/projects", show_recent = true, recent_items = 3, recent_trans_key = "recent_projects", more_trans_key = "more_projects" },
    { name = "blog", url = "$LANG_BASE_URL/blog", show_recent = true, recent_items = 3, recent_trans_key = "recent_blog_posts", more_trans_key = "more_blog_posts" },
    { name = "about", url = "$LANG_BASE_URL/about", show_recent = false },
]

[extra.images]
max_width = 2500

[extra.ogp]
locale = "en_US"
first_name = "Van"
last_name = "Nguyen"
gender = "male"
username = "vanbuncha"

[extra.social]
email = "van.nguyenn@protonmail.com"
github = "vanbuncha"
linkedin = "vanbuncha"
strava = "131186600"
other = []

[extra.cdn]
font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
